tap "d12frosted/emacs-plus"
tap "ferdium/ferdium"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"
tap "jez/formulae"
tap "romkatv/powerlevel10k"
tap "superfly/tap"
tap "ykursadkaya/openlens"
brew "ack"
brew "automake"
brew "azure-cli"
brew "bash"
brew "bat"
brew "btop"
brew "cocoapods"
brew "colima"
brew "container-structure-test"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "folly"
brew "entr"
brew "fswatch"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "gnupg", link: false
brew "harfbuzz"
brew "helm"
brew "htop"
brew "imagemagick"
brew "ispell"
brew "jq"
brew "jump"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "minikube"
brew "neovim"
brew "pre-commit"
brew "ripgrep"
brew "sbt"
brew "stern"
brew "subversion"
brew "talisman"
brew "tldr"
brew "tmux"
brew "trash"
brew "watch"
brew "watchman"
brew "wget"
brew "yq"
brew "zlib"
brew "zsh"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jez/formulae/git-heatmap"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "superfly/tap/flyctl"
cask "1password"
cask "azure-data-studio", args: { appdir: "/Applications" }
cask "boop"
cask "cheatsheet", args: { appdir: "/Applications" }
cask "cron"
cask "dash"
cask "discord"
cask "ferdium-nightly"
cask "fig"
cask "firefox"
cask "flux"
cask "flycut"
cask "font-source-code-pro"
cask "gimp"
cask "github"
cask "gitkraken"
cask "gpg-suite-no-mail"
cask "intellij-idea-ce", args: { appdir: "/Applications" }
cask "iterm2"
cask "lastpass"
cask "lepton"
cask "microsoft-remote-desktop"
cask "microsoft-teams", args: { appdir: "/Applications" }
cask "notion"
cask "openlens"
cask "parallels"
cask "postman", args: { appdir: "/Applications" }
cask "powershell"
cask "raycast"
cask "rectangle", args: { appdir: "/Applications" }
cask "rider", args: { appdir: "/Applications" }
cask "snagit"
cask "spotify", args: { appdir: "/Applications" }
cask "stats", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "zoom", args: { appdir: "/Applications" }
