tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"
tap "jez/formulae"
tap "romkatv/powerlevel10k"
tap "superfly/tap"
brew "ack"
brew "automake"
brew "bat"
brew "btop"
brew "colima"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "entr"
brew "folly"
brew "fswatch"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "gnupg"
brew "harfbuzz"
brew "htop"
brew "imagemagick"
brew "ispell"
brew "neovim"
brew "ripgrep"
brew "sbt"
brew "subversion"
brew "tmux"
brew "trash"
brew "watchman"
brew "wget"
brew "zlib"
brew "zsh"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jez/formulae/git-heatmap"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "superfly/tap/flyctl"
cask "azure-data-studio", args: { appdir: "/Applications" }
cask "background-music"
cask "boop"
cask "cheatsheet", args: { appdir: "/Applications" }
cask "dash"
cask "discord"
cask "emacs"
cask "ferdi", args: { appdir: "/Applications" }
cask "firefox"
cask "flux"
cask "flycut"
cask "font-source-code-pro"
cask "gitkraken"
cask "intellij-idea-ce", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "lastpass"
cask "lepton"
cask "microsoft-remote-desktop"
cask "microsoft-teams", args: { appdir: "/Applications" }
cask "notion"
cask "parallels"
cask "postman", args: { appdir: "/Applications" }
cask "raycast"
cask "rectangle", args: { appdir: "/Applications" }
cask "rider", args: { appdir: "/Applications" }
cask "snagit"
cask "spotify", args: { appdir: "/Applications" }
cask "stats", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "zoom", args: { appdir: "/Applications" }
